### PR TITLE
Fix storage feature after AniChan is updated with Workspace

### LINKED ISSUE #123: Fix Storage feature after AniChan is updated with Workspace
The storage feature was not working after AniChan is updated with Workspace as that has changed the overall logic of AniChan, hence, the codes pertaining to Storage will have to be updated to accommodate the new changes.

### PR DESCRIPTION
**Pull request by OngDeZhi**
Fix:
1. Storage feature.

Add: 
1. Different classes to handle storage for different classes (User, Watchlist, and Bookmark).
2. "data/" to .gitignore.

Update: 
1. Sample input and expected output.

@AY2021S1-CS2113T-F12-2/developers Take note: 
1. As the majority of us are using the Storage feature, do check and verify that the saving and loading is working for the features you are in charge of.
3. Your testing methods may or may not be working correctly now, so do check up on that too.

Fixes #123

### CODE REVIEW

**Review by n3wsoldier — APPROVED** [review]
LGTM :) 👍  💯

**Review by michaeldinata — APPROVED** [review]
Thanks for the hard work in fixing the storage! LGTM :))

**Review by EyoWeiChin — APPROVED** [review]
LGTM, Thanks!

**Review by ChanJianHao — APPROVED** [review]
LGTM!

**Pull request merged**
