### PR TITLE
Merge OngXinBin-AnimeList

### LINKED ISSUE #27: Add an AnimeData class
The AnimeList class will store anime catalog from our offline database, it will consist of functions related to using the anime database.

### PR DESCRIPTION
**Pull request by n3wsoldier**
Added
1) Create Anime list class
2) Get anime from list with index
3) Print all anime in animelist
4) Get the size of animelist
5) Provide basic usage example in duke.java

Closes #27

### CODE REVIEW

**Review by OngDeZhi — CHANGES_REQUESTED** [review]
The name you used for this class conflicts with the name I used for my ArrayList object in the Watchlist class, perhaps, you could change it to "AnimeData" or any other suitable names?

**Comment by n3wsoldier** [comment]
I understand your concerns regarding the conflict of the naming convention of AnimeList class and the array list object in the watchlist. I will take up your suggestion and rectify it to "AnimeData" to represent Animes from our offline data.

**Review by michaeldinata — APPROVED** [review]
Code looks good, but I think as De Zhi mentioned, you could change the "ArrayList" to some other suitable name so as to avoid conflicts!

**Review by OngDeZhi — APPROVED** [review]
LGTM :)

**Review by michaeldinata — APPROVED** [review]
AnimeData class checked and LGTM!

**Pull request merged**
