### PR TITLE
Merge MichaelDinata-ParserCommand

### LINKED ISSUE #59: Refactor: Parser Class

### LINKED ISSUE #60: Refactor: Command Class and Command Logic

### PR DESCRIPTION
**Pull request by michaeldinata**
Added:
1. Command class
2. Several sub-command classes inheriting the command class. We can then just call command.execute() to do the command

Refactored into sub-command classes:
1. CreateWatchlist class
2. AddToWatchlist class

Side-note: current execute() method takes in many parameters. Maybe we can change this once we refactor the other commands.

closes #59  
closes #60

### CODE REVIEW

**Review by ChanJianHao — APPROVED** [review]
Looks great, thanks Michael!

**Review by EyoWeiChin — APPROVED** [review]
Thanks for refactoring the Parser class and creating the Command Logic, LGTM to me!

**Review by OngDeZhi — APPROVED** [review]
LGTM :) Thanks for the hard work.

**Review by n3wsoldier — APPROVED** [review]
Thanks, LGTM :)

**Pull request merged**
