### PR TITLE
Merge OngDeZhi-Package

### LINKED ISSUE #30: Refactor: Organize classes into packages

### PR DESCRIPTION
**Pull request by OngDeZhi**
Organized the classes into packages.
Everybody will have to refactor their codes in the Duke.java into the respective classes in the packages.

Closes #30

### CODE REVIEW

**Review by n3wsoldier — APPROVED** [review]
LGTM :)

**Review by EyoWeiChin — APPROVED** [review]
Thanks for refactoring into packages! LGTM!

**Review by ChanJianHao — APPROVED** [review]
Good work! LGTM. 🥇

**Review by michaeldinata — APPROVED** [review]
LGTM!! 💯

**Pull request merged**
